# Generated by Django 3.1.7 on 2023-05-09 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.storages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'A user with that email address already exists.'}, max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_date', models.DateTimeField(blank=True, null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('ARCHIVE_CREATED', 'Archive Created')], default='ARCHIVE_CREATED', max_length=32)),
                ('callback_url', models.URLField()),
                ('signing_key', models.CharField(max_length=512)),
                ('signing_key_algorithm', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaptureJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed'), ('invalid', 'invalid')], db_index=True, default='pending', max_length=15)),
                ('message', models.JSONField(blank=True, null=True)),
                ('step_count', models.FloatField(default=0)),
                ('step_description', models.CharField(blank=True, max_length=255, null=True)),
                ('capture_start_time', models.DateTimeField(blank=True, null=True)),
                ('capture_end_time', models.DateTimeField(blank=True, null=True)),
                ('requested_url', models.CharField(blank=True, db_index=True, default='', max_length=2100)),
                ('label', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('webhook_data', models.CharField(blank=True, help_text='This string will be included, verbatim, in any webhook         notification response that you have subscribed to receive.', max_length=255, null=True)),
                ('validated_url', models.CharField(blank=True, max_length=2100, null=True)),
                ('human', models.BooleanField(default=False)),
                ('order', models.FloatField(db_index=True)),
                ('include_raw_exchanges', models.BooleanField(default=False)),
                ('include_screenshot', models.BooleanField(default=True)),
                ('include_pdf_snapshot', models.BooleanField(default=False)),
                ('include_dom_snapshot', models.BooleanField(default=False)),
                ('include_videos_as_attachment', models.BooleanField(default=True)),
                ('include_certificates_as_attachment', models.BooleanField(default=True)),
                ('run_site_specific_behaviors', models.BooleanField(default=True)),
                ('headless', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capture_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash', models.CharField(max_length=256)),
                ('hash_algorithm', models.CharField(max_length=32)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('download_url', models.URLField(max_length=2100, null=True)),
                ('download_expiration_timestamp', models.DateTimeField(null=True)),
                ('datapackage', models.JSONField()),
                ('datapackage_digest', models.CharField(max_length=256)),
                ('summary', models.JSONField()),
                ('capture_software', models.CharField(max_length=256)),
                ('partial_capture', models.BooleanField()),
                ('screenshot', models.FileField(blank=True, null=True, storage=main.storages.get_screenshot_storage, upload_to=main.storages.screenshot_directory)),
                ('capture_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='main.capturejob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='webhooksubscription',
            index=models.Index(fields=['user', 'event_type'], name='main_webhoo_user_id_acd3c0_idx'),
        ),
    ]
