# Generated by Django 3.1.7 on 2023-05-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturejob',
            name='include_certificates_as_attachment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='capturejob',
            name='include_dom_snapshot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capturejob',
            name='include_pdf_snapshot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capturejob',
            name='include_raw_exchanges',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capturejob',
            name='include_screenshot',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='capturejob',
            name='include_videos_as_attachment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='capturejob',
            name='run_site_specific_behaviors',
            field=models.BooleanField(default=True),
        ),
    ]
