# Generated by Django 3.1.7 on 2023-05-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230505_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='summary',
            field=models.JSONField(null=True),
        ),
    ]
