# Generated by Django 3.0.8 on 2020-09-23 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_webhooksubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobid', models.CharField(max_length=32)),
                ('hash', models.CharField(max_length=256)),
                ('hash_algorithm', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
