# Generated by Django 3.1.7 on 2023-05-08 20:12

from django.db import migrations, models
import main.storages


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_archive_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='screenshot',
            field=models.FileField(blank=True, null=True, storage=main.storages.get_screenshot_storage, upload_to=main.storages.screenshot_directory),
        ),
    ]
