# Generated by Django 3.0.8 on 2020-10-01 19:04

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='delivered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archive',
            name='requested_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 19, 4, 19, 538881, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
