# Generated by Django 3.1.7 on 2023-05-08 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_archive_screenshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='warc_size',
            new_name='size',
        ),
    ]
