# Generated by Django 3.0.8 on 2020-11-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201001_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='jobid',
            field=models.UUIDField(),
        ),
    ]
