# Generated by Django 3.0.8 on 2021-02-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210210_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturejob',
            name='webhook_data',
            field=models.CharField(blank=True, help_text='This string will be included, verbatim, in any webhook         notification response that you have subscribed to receive.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capturejob',
            name='label',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
