# Generated by Django 3.1.7 on 2021-02-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210219_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturejob',
            name='requested_url',
            field=models.CharField(blank=True, db_index=True, default='', max_length=2100),
        ),
        migrations.AlterField(
            model_name='capturejob',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed'), ('invalid', 'invalid')], db_index=True, default='pending', max_length=15),
        ),
    ]
