# Generated by Django 3.1.7 on 2021-02-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210224_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturejob',
            name='validated_url',
            field=models.CharField(blank=True, max_length=2100, null=True),
        ),
    ]
