# Generated by Django 3.1.7 on 2021-03-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_capturejob_validated_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturejob',
            name='message',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
