# Generated by Django 3.1.7 on 2021-03-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210302_1832'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='webhooksubscription',
            index=models.Index(fields=['user', 'event_type'], name='main_webhoo_user_id_acd3c0_idx'),
        ),
    ]
