# Generated by Django 3.1.7 on 2021-05-04 17:12

from django.db import migrations, models
import django.db.models.deletion
import main.storages


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210302_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCaptureJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed'), ('invalid', 'invalid')], db_index=True, default='pending', max_length=15)),
                ('message', models.JSONField(blank=True, null=True)),
                ('step_count', models.FloatField(default=0)),
                ('step_description', models.CharField(blank=True, max_length=255, null=True)),
                ('capture_start_time', models.DateTimeField(blank=True, null=True)),
                ('capture_end_time', models.DateTimeField(blank=True, null=True)),
                ('netloc', models.CharField(max_length=255)),
                ('headless', models.BooleanField(default=False)),
                ('screenshot', models.FileField(blank=True, null=True, storage=main.storages.get_profile_storage, upload_to=main.storages.profile_job_directory)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('netloc', models.CharField(max_length=255)),
                ('headless', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('marked_obsolete', models.DateTimeField(blank=True, null=True)),
                ('profile', models.FileField(storage=main.storages.get_profile_storage, upload_to=main.storages.profile_job_directory)),
                ('profile_capture_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='main.profilecapturejob')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
