# Generated by Django 3.1.7 on 2021-05-12 19:25

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_profile_profilecapturejob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecapturejob',
            name='netloc',
            field=models.CharField(max_length=255, validators=[main.models.validate_profile_netloc]),
        ),
    ]
