# Generated by Django 3.1.7 on 2021-05-12 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210512_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='created_with_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archives', to='main.profile'),
        ),
        migrations.AddField(
            model_name='capturejob',
            name='log_in_if_supported',
            field=models.BooleanField(default=True),
        ),
    ]
