# Generated by Django 3.1.7 on 2021-05-12 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210512_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='capture_job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='main.capturejob'),
        ),
    ]
