# Generated by Django 3.1.7 on 2021-06-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210512_2007'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['netloc', 'headless', 'verified', 'marked_obsolete'], name='main_profil_netloc_051df3_idx'),
        ),
    ]
